// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scale
arma::mat scale(const arma::mat& X, int dim);
RcppExport SEXP _X_ING_scale(SEXP XSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(scale(X, dim));
    return rcpp_result_gen;
END_RCPP
}
// unique
std::vector<int> unique(std::vector<int>& vec);
RcppExport SEXP _X_ING_unique(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(unique(vec));
    return rcpp_result_gen;
END_RCPP
}
// Lq_func
double Lq_func(arma::mat sjk_sqr, arma::mat mujk, arma::mat alphajk, arma::vec vk_sqr, arma::mat pik, arma::mat Lambda, arma::mat z);
RcppExport SEXP _X_ING_Lq_func(SEXP sjk_sqrSEXP, SEXP mujkSEXP, SEXP alphajkSEXP, SEXP vk_sqrSEXP, SEXP pikSEXP, SEXP LambdaSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type sjk_sqr(sjk_sqrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mujk(mujkSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alphajk(alphajkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vk_sqr(vk_sqrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type pik(pikSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(Lq_func(sjk_sqr, mujk, alphajk, vk_sqr, pik, Lambda, z));
    return rcpp_result_gen;
END_RCPP
}
// XING_starting
List XING_starting(arma::mat z, arma::mat Lambda, int iterT, double vk_init, double pi_init);
RcppExport SEXP _X_ING_XING_starting(SEXP zSEXP, SEXP LambdaSEXP, SEXP iterTSEXP, SEXP vk_initSEXP, SEXP pi_initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< int >::type iterT(iterTSEXP);
    Rcpp::traits::input_parameter< double >::type vk_init(vk_initSEXP);
    Rcpp::traits::input_parameter< double >::type pi_init(pi_initSEXP);
    rcpp_result_gen = Rcpp::wrap(XING_starting(z, Lambda, iterT, vk_init, pi_init));
    return rcpp_result_gen;
END_RCPP
}
// XING_single_data
List XING_single_data(const arma::mat& z, const arma::mat& Lambda, int PC, List result_starting, int iterT);
RcppExport SEXP _X_ING_XING_single_data(SEXP zSEXP, SEXP LambdaSEXP, SEXP PCSEXP, SEXP result_startingSEXP, SEXP iterTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Lambda(LambdaSEXP);
    Rcpp::traits::input_parameter< int >::type PC(PCSEXP);
    Rcpp::traits::input_parameter< List >::type result_starting(result_startingSEXP);
    Rcpp::traits::input_parameter< int >::type iterT(iterTSEXP);
    rcpp_result_gen = Rcpp::wrap(XING_single_data(z, Lambda, PC, result_starting, iterT));
    return rcpp_result_gen;
END_RCPP
}
// XING
List XING(const arma::mat& z1, const arma::mat& z2, const arma::mat& Lambda1, const arma::mat& Lambda2, int CC, int PC1, int PC2, const List& result_starting1, const List& result_starting2, const List& result_single1, const List& result_single2, int iterT);
RcppExport SEXP _X_ING_XING(SEXP z1SEXP, SEXP z2SEXP, SEXP Lambda1SEXP, SEXP Lambda2SEXP, SEXP CCSEXP, SEXP PC1SEXP, SEXP PC2SEXP, SEXP result_starting1SEXP, SEXP result_starting2SEXP, SEXP result_single1SEXP, SEXP result_single2SEXP, SEXP iterTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z1(z1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type z2(z2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Lambda1(Lambda1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Lambda2(Lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type CC(CCSEXP);
    Rcpp::traits::input_parameter< int >::type PC1(PC1SEXP);
    Rcpp::traits::input_parameter< int >::type PC2(PC2SEXP);
    Rcpp::traits::input_parameter< const List& >::type result_starting1(result_starting1SEXP);
    Rcpp::traits::input_parameter< const List& >::type result_starting2(result_starting2SEXP);
    Rcpp::traits::input_parameter< const List& >::type result_single1(result_single1SEXP);
    Rcpp::traits::input_parameter< const List& >::type result_single2(result_single2SEXP);
    Rcpp::traits::input_parameter< int >::type iterT(iterTSEXP);
    rcpp_result_gen = Rcpp::wrap(XING(z1, z2, Lambda1, Lambda2, CC, PC1, PC2, result_starting1, result_starting2, result_single1, result_single2, iterT));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_X_ING_scale", (DL_FUNC) &_X_ING_scale, 2},
    {"_X_ING_unique", (DL_FUNC) &_X_ING_unique, 1},
    {"_X_ING_Lq_func", (DL_FUNC) &_X_ING_Lq_func, 7},
    {"_X_ING_XING_starting", (DL_FUNC) &_X_ING_XING_starting, 5},
    {"_X_ING_XING_single_data", (DL_FUNC) &_X_ING_XING_single_data, 5},
    {"_X_ING_XING", (DL_FUNC) &_X_ING_XING, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_X_ING(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
