# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scale <- function(X, dim = 0L) {
    .Call(`_X_ING_scale`, X, dim)
}

unique <- function(vec) {
    .Call(`_X_ING_unique`, vec)
}

Lq_func <- function(sjk_sqr, mujk, alphajk, vk_sqr, pik, Lambda, betahat) {
    .Call(`_X_ING_Lq_func`, sjk_sqr, mujk, alphajk, vk_sqr, pik, Lambda, betahat)
}

XING_starting <- function(betahat, Lambda, iterT = 10L, eps_thres = 1e-3, vk_init = 0.1, bound = 1e-4, pi_init = 0.1) {
    .Call(`_X_ING_XING_starting`, betahat, Lambda, iterT, eps_thres, vk_init, bound, pi_init)
}

XING_single_data <- function(betahat, Lambda, PC = 2L, results_alg1 = NULL, eps_thresh = 1e-2, iterT = 5L, use_true_X = FALSE, bound = 1e-4) {
    .Call(`_X_ING_XING_single_data`, betahat, Lambda, PC, results_alg1, eps_thresh, iterT, use_true_X, bound)
}

XING <- function(betahat1, betahat2, Lambda1, Lambda2, CC, PC1, PC2, results_alg1_dat1, results_alg1_dat2, results_alg2_dat1, results_alg2_dat2, eps_thresh = 1e-2, iterT = 20L, bound = 1e-4) {
    .Call(`_X_ING_XING`, betahat1, betahat2, Lambda1, Lambda2, CC, PC1, PC2, results_alg1_dat1, results_alg1_dat2, results_alg2_dat1, results_alg2_dat2, eps_thresh, iterT, bound)
}

